### ISSUE TITLE
Error in cox regression

### ISSUE THREAD

**Issue by benben-miao** [yikeshu0611/ggDCA#1]
```
> model1 <- coxph(Surv(time,status)~ANLN,LIRI)
> d <- dca(model1,model.names = 'ANLN')
Error in findrow(fit, times, extend) : 
  no points selected for one or more curves, consider using the extend argument
> ggplot(d)
Error in ggplot(d) : object 'd' not found
```

**Comment by tomato08217** [comment]
Hi I got that error,too. Did you resolve that?

**Comment by yikeshu0611** [comment]
> ```
> > model1 <- coxph(Surv(time,status)~ANLN,LIRI)
> > d <- dca(model1,model.names = 'ANLN')
> Error in findrow(fit, times, extend) : 
>   no points selected for one or more curves, consider using the extend argument
> > ggplot(d)
> Error in ggplot(d) : object 'd' not found
> ```

update survival package to the latest version

**Comment by yikeshu0611** [comment]
> Hi I got that error,too. Did you resolve that?

update survival package to the latest version

**Comment by yikeshu0611** [comment]
use github version to solve this problem
